### ISSUE TITLE
FR: Could we get sensors for high and low temps and a description of what the weather will look like?

### ISSUE THREAD

**Issue by scstraus** [briis/hass-weatherflow#49]
Hi, 

First off, thanks for a great integration, it's serving me super well, and I find the forecasts to be a lot more accurate than any of the other weather integrations (and I've tried them all).  As I am slowly preparing for the end of the dark sky integration, and this works better anyway, I thought I'd hit you up for a few more sensors if possible. I use these to control my heating system, so the increased accuracy from this integraiton would be super useful. A few of the ones that dark sky provides that would help me a lot are these ones:

- a sensor for the high temperature in today's forecast
- a sensor for the low temperature in today's forecast
- a description of the general weather conditions for the day (in the dark sky integration, this is shown as the icon, but I find it very useful as a single variable to control automations too). The possible options are 
         'partly-cloudy-day', 'rain', 'snow', 'sleet', 'wind', 'fog', 'cloudy','clear-day'
         
Thanks for the consideration.

**Comment by briis** [comment]
While you wait for me to do this, you can actually really easy make these three sensors as template sensors yourself. I have added and example below:

```yaml
- name: Temperature Day High
   unique_id: some_unique_id
   icon: mdi:thermometer
   state: >
      {{ "%0.1f" | format(state_attr('weather.weatherflow_day_based_forecast', 'forecast')[0].temperature | float(default=0) ) }}
- name: Temperature Day Low
   unique_id: some_unique_id
   icon: mdi:thermometer
   state: >
      {{ "%0.1f" | format(state_attr('weather.weatherflow_day_based_forecast', 'forecast')[0].templow | float(default=0) ) }}
- name: Current Condition
   unique_id: some_unique_id
   icon: mdi:weather-partly-cloudy
   state: >
      {{ state_attr('weather.weatherflow_day_based_forecast', 'forecast')[0].condition }}
````
